default: example.c
	gcc example.c -o example -L/usr/local/lib/ -I/usr/local/include/lintegrate -llintegrate -lm -lgsl -lgslcblas

flat: example_flat.c
	gcc example_flat.c -o example_flat -L/usr/local/lib/ -I/usr/local/include/lintegrate -llintegrate -lm -lgsl -lgslcblas

split: example_split.c
	gcc example_split.c -o example_split -L/usr/local/lib/ -I/usr/local/include/lintegrate -llintegrate -lm -lgsl -lgslcblas
