# This workflow to run the test suite for lintegrate (based on the default workflow)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
        include:
          - os: ubuntu-20.04
            ccompiler: "c-compiler"
            condainstall: "numpy pip pytest setuptools"
          - os: ubuntu-22.04
            ccompiler: "numpy pip pytest setuptools"
          - os: windows-latest
            condainstall: "c-compiler cython gsl numpy pip pytest setuptools"
          - os: macos-latest
            condainstall: "c-compiler 'clang>=12.0.1' cython gsl numpy pip pytest setuptools"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04' }}
      run: |
        apt install libgsl-dev
        apt list --installed | grep gsl
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda install -n test -q -y ${{ matrix.condainstall }}
    - name: Conda information
      run: |
        conda info --all
        conda list -n test
    - name: Install lintegrate
      run: |
        python -m pip install -e . -vv --no-build-isolation
    - name: Run test suite
      run: |
        python -m pytest
